version: "3"
services:
  database:
    container_name: bugtracker_database
    image: mysql:8
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=domiklein
      - MYSQL_DATABASE=bugtracker
    ports:
      - "3306:3306"
    volumes:
      - ./database/data/docker:/var/lib/mysql
      # - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
