# Logging
logging:
  file:
    path: logs
  level:
    root: warn
    com.bugtracker: info
    org.springframework: info
# Database
spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bugtracker
    username: root
    password: domiklein
# JWT - Used key, if non specified
klein:
  bugtracker:
    jwt:
      key: iyX29o7w93EcsRfJ6qVf2axnfFKixcDuwhY6zW5HksUkeqvGkLC5BBC5Hh9YcTDqg8QGwUSMRMsWAbq4YWPbJ7CnUfz3pAiNdxaVo8g4nZ7XPgW7C8txqW4dzENkp4mf
